### ISSUE TITLE
Error loading mod

### ISSUE THREAD

**Issue by Eugenii10** [theRustyKnife/FireproofBots#1]
Hello!
Thanks for a mod!
But I have troubles with loading it.
![error_loading](https://cloud.githubusercontent.com/assets/26702097/26031082/246dc1f4-38aa-11e7-94e4-1c67e4bbabb9.png)
Here the list of mods: https://pastebin.com/fQ1furfq
The one that comes to mind is data-raw-prototypes_0.3.1 by Earendel. Maybe it conflicts with your mod?
*Factorio 0.15.10

**Comment by theRustyKnife** [comment]
Fixed this in 1.0.1. It was caused by Bob's Logistics having bots with no resistances defined before my mod came to change them.
Cheers TRK
